# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb", "1700"]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.1.4
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
        files: ^aiopynetdicom/.*\.py$
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
